# Generated by Django 5.2.7 on 2025-11-07 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bemorlar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(choices=[('1', 'Erkak'), ('2', 'Ayol')], max_length=10)),
                ('diagnosis', models.TextField()),
                ('doctor_name', models.CharField(max_length=128)),
            ],
        ),
    ]
