# Generated by Django 5.2.7 on 2025-11-07 19:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dorilar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dori_name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, help_text='Dori haqida qo‘shimcha izoh', null=True)),
                ('once_in_day', models.SmallIntegerField(help_text='Kuniga necha marta ichiladi')),
                ('dosage', models.CharField(blank=True, help_text='Masalan: 1 dona, 2 ml, 1 tabletka', max_length=50, null=True)),
                ('usage_time', models.CharField(blank=True, help_text='Masalan: Ertalab, Kechqurun, Ovqatdan keyin', max_length=100, null=True)),
                ('doctor_name', models.CharField(blank=True, help_text='Dorini yozgan shifokor', max_length=100, null=True)),
                ('created_at', models.DateTimeField()),
                ('finish_at', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True, help_text='Dori ichish muddati tugaganmi yo‘qmi')),
                ('bemor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dorilar', to='users.bemorlar')),
            ],
        ),
    ]
